In [ ]:
Create a random vector of size 30 and find the mean value

In [7]:
import numpy as np
a=np.arange(0,30).reshape(5,6)
print(a)

np.mean(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


14.5