In [ ]:
Sort following NumPy array

Case 1: Sort array by the second row
Case 2: Sort the array by the second column
    
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

In [4]:
import numpy as np

sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [16]:
print("Sorting Original array by secoond row")

sortArrayByRow = sampleArray[:,sampleArray[1,:].argsort()]

print(sortArrayByRow)

Sorting Original array by secoond row
[[73 43 34]
 [12 22 82]
 [66 94 53]]


In [17]:
print("Sorting Original array by secoond column")

sortArrayByColumn = sampleArray[sampleArray[:,1].argsort()]

print(sortArrayByColumn)

Sorting Original array by secoond column
[[82 22 12]
 [34 43 73]
 [53 94 66]]
