In [ ]:
Split the array into four equal-sized sub-arrays
Note: Create an 8X3 integer array from a range between 10 to 34 such that the difference between each 
element is 1 and then Split the array into four equal-sized sub-arrays.

In [2]:
import numpy as np

a =np.arange(10,34).reshape(8,3)
a

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [4]:
np.vsplit(a,4)

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]