___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

## Numpy Review

In [3]:
ls = [1, 2, 3]
ls

[1, 2, 3]

In [4]:
copy = ls
copy

[1, 2, 3]

In [6]:
copy.append("Quinn")
copy

[1, 2, 3, 'Quinn', 'Quinn']

In [7]:
ls

[1, 2, 3, 'Quinn', 'Quinn']

In [9]:
id(ls)

2050837271808

In [12]:
clean = ls.copy()

In [10]:
id(copy)

2050837271808

In [13]:
id(clean)

2050837306368

### Constructors and References

In [14]:
import numpy as np
import pandas as pd

In [15]:
ls = [1, 2, 3, 4, 5, 6]
a = np.array(ls)
a

array([1, 2, 3, 4, 5, 6])

In [18]:
a[0:3]

array([1, 2, 3])

In [19]:
a[-1]

6

In [21]:
a[-2:]

array([5, 6])

In [22]:
a[0] = 666
a

array([666,   2,   3,   4,   5,   6])

In [24]:
a[3:6] = 777
a

array([666,   2,   3, 777, 777, 777])

In [26]:
type(a)

numpy.ndarray

In [27]:
b = a[::]  #[start, stop, stride]  [0, end, 1]

In [28]:
id(a) == id(b)

False

In [29]:
a[::-1]

array([777, 777, 777,   3,   2, 666])

In [30]:
np.zeros( (3, 5)) # random, ones, full, empty   np.<whatever>
#np.eye (identity matrix)  #linspace()

<function numpy.zeros>

In [32]:
z = np.random.randint(2,15, size = (5,3))
z

array([[ 7, 14,  9],
       [ 5,  2,  4],
       [12, 12,  9],
       [ 7,  7,  3],
       [ 9, 12,  6]])

In [33]:
z.shape

(5, 3)

In [34]:
z.size

15

In [36]:
z.dtype

dtype('int32')

In [37]:
floaty_z = z.astype(float)

array([[ 7., 14.,  9.],
       [ 5.,  2.,  4.],
       [12., 12.,  9.],
       [ 7.,  7.,  3.],
       [ 9., 12.,  6.]])

In [38]:
z

array([[ 7, 14,  9],
       [ 5,  2,  4],
       [12, 12,  9],
       [ 7,  7,  3],
       [ 9, 12,  6]])

In [41]:
z.reshape(3, 5)



array([[ 7, 14,  9,  5,  2],
       [ 4, 12, 12,  9,  7],
       [ 7,  3,  9, 12,  6]])

In [43]:
z.T


array([[ 7,  5, 12,  7,  9],
       [14,  2, 12,  7, 12],
       [ 9,  4,  9,  3,  6]])

In [44]:
z.max()

14

In [45]:
z.min()

2

In [ ]:
#stdev mean  ... 

In [48]:
r = z.ravel()

In [49]:
type(r)

numpy.ndarray

In [56]:
my_arr = np.array([0,1,2,3,4,5,6,7,8,9]).reshape(5,2)
my_arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [57]:
my_arr_1 = np.array([3,4,5,6,7,8,9,10,11,12]).reshape(5,2)
my_arr_1

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [65]:
np.concatenate([my_arr_1, my_arr], axis=0)

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9]])

In [ ]:
np.stack

In [67]:
array_1 = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]])
array_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
array_1 > 4  # <  > >=  <=  ==  

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [69]:
array_1 [ array_1 > 4    ]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [70]:
array_1[(array_1<10) & (array_1>3)]   # &  |  ^ 

array([4, 5, 6, 7, 8, 9])

In [71]:
# element-wise operations
array_1 + array_1  # + - * / **   NaN  

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [74]:
s = pd.Series ([1, 2, 4])

In [75]:
s.values

array([1, 2, 4], dtype=int64)

In [77]:
s.index = ['one', 'two', 'three']
s

one      1
two      2
three    4
dtype: int64

In [79]:
s['one']

1

In [80]:
s['one':'three']

one      1
two      2
three    4
dtype: int64